### ISSUE TITLE
cm doesn't kill process on exit

### ISSUE THREAD

**Issue by travisstaloch** [tsoding/cm#218]
Running the following and quitting cm doesn't kill the process on linux. I have to manually kill it.
Related #101 

```sh
$ cat tmp.c
void main() {
	while (1) {};
}

$ gcc tmp.c

$ cm ./a.out
```

**Comment by rexim** [comment]
This happens because we are not running the commands directly, we are running them indirectly via a shell.

```
cm -> shell -> your commands
```

And even tho cm kills the shell (using SIGKILL, because of the Rust std lib) the child process of the shell itself may not be killed for whatever reason.

We need to do more research on
- what signal we need to send to the shell to kill everything properly?
- will that signal work for all of the shells on the market?
- is there any standard that specifies the shell's behavior regarding killing children processes on receiving particular signals?
- if nothing is standardized what kind of UX measures we need to implement to smooth out the support for as many shells as possible?

**Comment by travisstaloch** [comment]
A couple of messages from chat you may have missed while typing up the previous message:

> herrhotzenplotz:I just looked at the source of bash. They ARE using sigaction(2) instead of signal(2)

> LostAlgorithm:I just looked at how a few other programs suggest to do this, in python you'd use a process group construct that tracks what that shell spawns and signals everything in that list I'd guess

**Comment by travisstaloch** [comment]
If you're interested in trying to use a process group, here is a commit i found that does this in rust.  https://github.com/watchexec/watchexec/commit/f3c6df8845ed13e231cd9cbd88afdebe5fd97569

When this commit was made, `before_exec` was in nightly I think.  It now resides at `std::os::unix::process::CommandExt::pre_exec`.

**Comment by rexim** [comment]
@travisstaloch this looks like a very useful information! Thank you very much! I tried to apply it in #227. Please check it out when you get a chance and close this issue if it works for you.

**Comment by travisstaloch** [comment]
Looks great! Seems to work for me. :+1: 
btw: `pgrep main` and `pkill main` are nice shortcuts for `ps ... | grep main` and `kill pid`
